#region Header
// -----------------------------------------------------------------------
//  <copyright file="OpenApiConstants.cs" company="INVENTIO AG">
//      Copyright © 2023 INVENTIO AG
//      All rights reserved.
//      INVENTIO AG, Seestrasse 55, CH-6052 Hergiswil, owns and retains all copyrights and other intellectual property rights in this
//      document. Any reproduction, translation, copying or storing in data processing units in any form or by any means without prior
//      permission of INVENTIO AG is regarded as infringement and will be prosecuted.
// 
//      'CONFIDENTIAL'
//      This document contains confidential information that is proprietary to the Schindler Group. Neither this document nor the
//      information contained herein shall be disclosed to third parties nor used for manufacturing or any other application without
//      written consent of INVENTIO AG.
//  </copyright>
// -----------------------------------------------------------------------
#endregion

namespace AutoNotionTube.Core.Constants
{
    public static class OpenApiConstants
    {
        public const string Start =
            "Please note that the following text(captures from video) has been automatically generated by a machine and may contain inaccuracies, please bear this in mind but disregard just follow the general context. Also please give me only the final result for all your next answers without your additional comments like - (Here is your summary: result... or Sure, here are the steps or instructions:  result...)";

        public const string Summarize = "Summarize this text: ";

        public const string Steps = "Create a list of steps or instruction from you previous summarize answer? (please note if you won't find further steps or instructions from you previous summarize answer, please just answer with 'no steps')";

        public const string ShortSummarize =
            "Give me a super short extract from your summary in simple words, just as a desktop shortcut just for my brain from this text?";

        public const string Tags =
            "Give me a list of tags from your full summary for my notion note separated by comma and -PascalCase (example : -MyTag1, -MyTag2, -MyTag4) (please note if you won't find further tags from you previous summarize answer, please just answer with 'no tags')";
    }
}
